namespace Domain.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Initial : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Dodatoc1",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Input_1_посада_ініціали_прізвище = c.String(),
                        Input_2_підпис = c.String(),
                        Input_3_число = c.String(),
                        Input_4_місяць = c.String(),
                        Input_5_рік = c.String(),
                        Input_6_номер_акту = c.String(),
                        Input_7_П_І_Б_Потерпілого = c.String(),
                        Input_8_Рік_Народження = c.String(),
                        Input_9_Навч_Заклад_Клас_Група = c.String(),
                        Input_10_Підпорядкованість_Належність = c.String(),
                        Input_11_Поштовий_Індекс_Адреса = c.String(),
                        Input_12_Місце_Нещасності = c.String(),
                        Input_13_П_І_Б_Вихователя = c.String(),
                        Input_14_Інструктаж_Вступний = c.String(),
                        Input_15_Інструктаж_Первинний = c.String(),
                        Input_16_Дата_Нещасного_Випадку = c.String(),
                        Input_17_Обставини_Нещасності = c.String(),
                        Input_18_Подія_Нещасності = c.String(),
                        Input_19_Причини_Нещасності = c.String(),
                        Input_20_Наслідки_Нещасності = c.String(),
                        Input_21_Стан_Потерпілого = c.String(),
                        Input_22_Особи_Порушники = c.String(),
                        Input_23_Свідки_Єгови = c.String(),
                        Input_24_Число = c.String(),
                        Input_25_Місяць = c.String(),
                        Input_26_Рік = c.String(),
                        Input_27_Голова_Комісії_Посада = c.String(),
                        Input_28_Голова_Комісії_Підпис = c.String(),
                        Input_29_Члени_Комісії_Посада = c.String(),
                        Input_30_Члени_Комісії_Підпис = c.String(),
                        Input_31_Члени_Комісії_Посада = c.String(),
                        Input_32_Голова_Комісії_Підпис = c.String(),
                        Input_33_Члени_Комісії_Посада = c.String(),
                        Input_34_Голова_Комісії_Підпис = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Dodatoc2",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Input_1_орган_управління_освітою = c.String(),
                        Input_2_п_і_б = c.String(),
                        Input_3_навчальний_заклад = c.String(),
                        Input_4_клас_група = c.String(),
                        Input_5_номер_акту_форми = c.String(),
                        Input_6_число = c.String(),
                        Input_7_місяць = c.String(),
                        Input_8_рік = c.String(),
                        Input_9_керівник_закладу = c.String(),
                        Input_10_ініціали_прізвище = c.String(),
                        Input_11_число = c.String(),
                        Input_12_місяць = c.String(),
                        Input_13_рік = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Dodatoc4",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Input_1_орган_управління_освітою = c.String(),
                        Input_2_дата_час_нещасності = c.String(),
                        Input_3_назва_навчального_закладу = c.String(),
                        Input_4_місце_нещасності = c.String(),
                        Input_5_дані_потерпілих = c.String(),
                        Input_6_характер_травм = c.String(),
                        Input_7_обставини_нещасності = c.String(),
                        Input_8_дата_передачі_інформації = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Dodatoc5",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Input_1_число = c.String(),
                        Input_2_місяць = c.String(),
                        Input_3_рік = c.String(),
                        Input_4_година = c.String(),
                        Input_5_хвилина = c.String(),
                        Input_6_назва_закладу_засновника = c.String(),
                        Input_7_число = c.String(),
                        Input_8_місяць = c.String(),
                        Input_9_рік = c.String(),
                        Input_10_місце_складання_акта = c.String(),
                        Input_11_число = c.String(),
                        Input_12_місяць = c.String(),
                        Input_13_рік = c.String(),
                        Input_14_номер = c.String(),
                        Input_15_назва_органу = c.String(),
                        Input_16_голова_комісії_п_і_б = c.String(),
                        Input_17_голова_комісії_посада = c.String(),
                        Input_18_члени_комісії_п_і_б = c.String(),
                        Input_19_члени_комісії_посада = c.String(),
                        Input_20_члени_комісії_п_і_б = c.String(),
                        Input_21_члени_комісії_посада = c.String(),
                        Input_22_члени_комісії_п_і_б = c.String(),
                        Input_23_члени_комісії_посада = c.String(),
                        Input_24_члени_комісії_п_і_б = c.String(),
                        Input_25_члени_комісії_посада = c.String(),
                        Input_26_члени_комісії_п_і_б = c.String(),
                        Input_27_члени_комісії_посада = c.String(),
                        Input_28_число = c.String(),
                        Input_29_місяць = c.String(),
                        Input_30_рік = c.String(),
                        Input_31_число = c.String(),
                        Input_32_місяць = c.String(),
                        Input_33_рік = c.String(),
                        Input_34_місце_події = c.String(),
                        Input_35_п_і_б_рік_клас_і_тд_потерпілого = c.String(),
                        Input_36_обставини_нещасності = c.String(),
                        Input_37_причини_нещасності = c.String(),
                        Input_38_заходи_усунення_нещасності = c.String(),
                        Input_39_висновки = c.String(),
                        Input_40_голова_комісії_посада = c.String(),
                        Input_41_голова_комісії_п_і_б = c.String(),
                        Input_42_голова_комісії_посада = c.String(),
                        Input_43_голова_комісії_п_і_б = c.String(),
                        Input_44_голова_комісії_посада = c.String(),
                        Input_45_голова_комісії_п_і_б = c.String(),
                        Input_46_голова_комісії_посада = c.String(),
                        Input_47_голова_комісії_п_і_б = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.DynamicTables",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        EntityId = c.Int(nullable: false),
                        ColumnsCount = c.Int(nullable: false),
                        RowsCount = c.Int(nullable: false),
                        DataRaw = c.String(),
                        TableTag = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Forma7",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Input_1_код = c.String(),
                        Input_2_код = c.String(),
                        Input_3_код = c.String(),
                        Input_4_код = c.String(),
                        Input_5_код = c.String(),
                        Input_6_код = c.String(),
                        Input_7_код = c.String(),
                        Input_8_код = c.String(),
                        Input_9_рік = c.String(),
                        Input_10_респондент_найменування = c.String(),
                        Input_11_респондент_місцезнаходження = c.String(),
                        Input_12_респондент_адреса = c.String(),
                        Input_13_т_7_р_3_к_3 = c.String(),
                        Input_13_т_7_р_4_к_3 = c.String(),
                        Input_13_т_7_р_5_к_3 = c.String(),
                        Input_14_т_9_р_4_к_3 = c.String(),
                        Input_15_т_9_р_4_к_4 = c.String(),
                        Input_16_т_9_р_5_к_3 = c.String(),
                        Input_17_т_9_р_5_к_4 = c.String(),
                        Input_18_т_9_р_6_к_3 = c.String(),
                        Input_19_т_9_р_6_к_4 = c.String(),
                        Input_20_т_9_р_7_к_3 = c.String(),
                        Input_21_т_9_р_7_к_4 = c.String(),
                        Input_22_т_9_р_8_к_3 = c.String(),
                        Input_23_т_9_р_8_к_4 = c.String(),
                        Input_24_т_9_р_9_к_3 = c.String(),
                        Input_25_т_9_р_9_к_4 = c.String(),
                        Input_26_т_9_р_10_к_3 = c.String(),
                        Input_27_т_9_р_10_к_4 = c.String(),
                        Input_28_т_9_р_11_к_3 = c.String(),
                        Input_29_т_9_р_11_к_4 = c.String(),
                        Input_30_т_9_р_12_к_3 = c.String(),
                        Input_31_т_9_р_12_к_4 = c.String(),
                        Input_32_т_9_р_13_к_3 = c.String(),
                        Input_33_т_9_р_13_к_4 = c.String(),
                        Input_34_т_9_р_14_к_3 = c.String(),
                        Input_35_т_9_р_14_к_4 = c.String(),
                        Input_36_т_9_р_15_к_3 = c.String(),
                        Input_37_т_9_р_15_к_4 = c.String(),
                        Input_38_т_9_р_16_к_3 = c.String(),
                        Input_39_т_9_р_16_к_4 = c.String(),
                        Input_40_т_9_р_17_к_3 = c.String(),
                        Input_41_т_9_р_17_к_4 = c.String(),
                        Input_42_т_9_р_18_к_3 = c.String(),
                        Input_43_т_9_р_18_к_4 = c.String(),
                        Input_44_т_9_р_19_к_3 = c.String(),
                        Input_45_т_9_р_19_к_4 = c.String(),
                        Input_46_т_9_р_20_к_3 = c.String(),
                        Input_47_т_9_р_20_к_4 = c.String(),
                        Input_48_т_10_р_3_к_3 = c.String(),
                        Input_49_т_10_р_3_к_4 = c.String(),
                        Input_50_т_10_р_3_к_5 = c.String(),
                        Input_51_т_10_р_4_к_3 = c.String(),
                        Input_52_т_10_р_4_к_4 = c.String(),
                        Input_53_т_10_р_4_к_5 = c.String(),
                        Input_54_т_10_р_5_к_3 = c.String(),
                        Input_55_т_10_р_5_к_4 = c.String(),
                        Input_56_т_10_р_5_к_5 = c.String(),
                        Input_57_т_10_р_6_к_3 = c.String(),
                        Input_58_т_10_р_7_к_3 = c.String(),
                        Input_59_т_10_р_7_к_4 = c.String(),
                        Input_60_т_10_р_7_к_5 = c.String(),
                        Input_61_т_11_р_5_к_3 = c.String(),
                        Input_62_т_11_р_5_к_4 = c.String(),
                        Input_63_т_11_р_5_к_5 = c.String(),
                        Input_64_т_11_р_5_к_6 = c.String(),
                        Input_65_т_11_р_6_к_3 = c.String(),
                        Input_66_т_11_р_6_к_4 = c.String(),
                        Input_67_т_11_р_6_к_5 = c.String(),
                        Input_68_т_11_р_6_к_6 = c.String(),
                        Input_69_т_11_р_7_к_3 = c.String(),
                        Input_70_т_11_р_7_к_4 = c.String(),
                        Input_71_т_11_р_7_к_5 = c.String(),
                        Input_72_т_11_р_7_к_6 = c.String(),
                        Input_73_т_11_р_8_к_3 = c.String(),
                        Input_74_т_11_р_8_к_4 = c.String(),
                        Input_75_т_11_р_8_к_5 = c.String(),
                        Input_76_т_11_р_8_к_6 = c.String(),
                        Input_77_т_11_р_9_к_3 = c.String(),
                        Input_78_т_11_р_9_к_4 = c.String(),
                        Input_79_т_11_р_9_к_5 = c.String(),
                        Input_80_т_11_р_9_к_6 = c.String(),
                        Input_81_т_11_р_10_к_3 = c.String(),
                        Input_82_т_11_р_10_к_4 = c.String(),
                        Input_83_т_11_р_10_к_5 = c.String(),
                        Input_84_т_11_р_10_к_6 = c.String(),
                        Input_85_т_11_р_11_к_3 = c.String(),
                        Input_86_т_11_р_11_к_4 = c.String(),
                        Input_87_т_11_р_11_к_5 = c.String(),
                        Input_88_т_11_р_11_к_6 = c.String(),
                        Input_89_т_11_р_12_к_3 = c.String(),
                        Input_90_т_11_р_12_к_4 = c.String(),
                        Input_91_т_11_р_12_к_5 = c.String(),
                        Input_92_т_11_р_12_к_6 = c.String(),
                        Input_93_т_11_р_13_к_3 = c.String(),
                        Input_94_т_11_р_13_к_4 = c.String(),
                        Input_95_т_11_р_13_к_5 = c.String(),
                        Input_96_т_11_р_13_к_6 = c.String(),
                        Input_97_т_11_р_14_к_3 = c.String(),
                        Input_98_т_11_р_14_к_4 = c.String(),
                        Input_99_т_11_р_14_к_5 = c.String(),
                        Input_100_т_11_р_14_к_6 = c.String(),
                        Input_101_т_11_р_15_к_3 = c.String(),
                        Input_102_т_11_р_15_к_4 = c.String(),
                        Input_103_т_11_р_15_к_5 = c.String(),
                        Input_104_т_11_р_15_к_6 = c.String(),
                        Input_105_т_11_р_16_к_3 = c.String(),
                        Input_106_т_11_р_16_к_4 = c.String(),
                        Input_107_т_11_р_16_к_5 = c.String(),
                        Input_108_т_11_р_16_к_6 = c.String(),
                        Input_109_т_11_р_17_к_3 = c.String(),
                        Input_110_т_11_р_17_к_4 = c.String(),
                        Input_111_т_11_р_17_к_5 = c.String(),
                        Input_112_т_11_р_17_к_6 = c.String(),
                        Input_113_т_11_р_18_к_3 = c.String(),
                        Input_114_т_11_р_18_к_4 = c.String(),
                        Input_115_т_11_р_18_к_5 = c.String(),
                        Input_116_т_11_р_18_к_6 = c.String(),
                        Input_117_т_11_р_19_к_3 = c.String(),
                        Input_118_т_11_р_19_к_4 = c.String(),
                        Input_119_т_11_р_19_к_5 = c.String(),
                        Input_120_т_11_р_19_к_6 = c.String(),
                        Input_121_т_11_р_20_к_3 = c.String(),
                        Input_122_т_11_р_20_к_4 = c.String(),
                        Input_123_т_11_р_20_к_5 = c.String(),
                        Input_124_т_11_р_20_к_6 = c.String(),
                        Input_125_т_11_р_21_к_3 = c.String(),
                        Input_126_т_11_р_21_к_4 = c.String(),
                        Input_127_т_11_р_21_к_5 = c.String(),
                        Input_128_т_11_р_21_к_6 = c.String(),
                        Input_129_т_11_р_22_к_3 = c.String(),
                        Input_130_т_11_р_22_к_4 = c.String(),
                        Input_131_т_11_р_22_к_5 = c.String(),
                        Input_132_т_11_р_22_к_6 = c.String(),
                        Input_133_т_11_р_23_к_3 = c.String(),
                        Input_134_т_11_р_23_к_4 = c.String(),
                        Input_135_т_11_р_23_к_5 = c.String(),
                        Input_136_т_11_р_23_к_6 = c.String(),
                        Input_137_т_11_р_24_к_3 = c.String(),
                        Input_138_т_11_р_24_к_4 = c.String(),
                        Input_139_т_11_р_24_к_5 = c.String(),
                        Input_140_т_11_р_24_к_6 = c.String(),
                        Input_141_т_12_р_5_к_3 = c.String(),
                        Input_142_т_12_р_5_к_4 = c.String(),
                        Input_143_т_12_р_5_к_5 = c.String(),
                        Input_144_т_12_р_5_к_6 = c.String(),
                        Input_145_т_12_р_6_к_3 = c.String(),
                        Input_146_т_12_р_6_к_4 = c.String(),
                        Input_147_т_12_р_6_к_5 = c.String(),
                        Input_148_т_12_р_6_к_6 = c.String(),
                        Input_149_т_12_р_7_к_3 = c.String(),
                        Input_150_т_12_р_7_к_4 = c.String(),
                        Input_151_т_12_р_7_к_5 = c.String(),
                        Input_152_т_12_р_7_к_6 = c.String(),
                        Input_153_т_12_р_8_к_3 = c.String(),
                        Input_154_т_12_р_8_к_4 = c.String(),
                        Input_155_т_12_р_8_к_5 = c.String(),
                        Input_156_т_12_р_8_к_6 = c.String(),
                        Input_157_т_12_р_9_к_3 = c.String(),
                        Input_158_т_12_р_9_к_4 = c.String(),
                        Input_159_т_12_р_9_к_5 = c.String(),
                        Input_160_т_12_р_9_к_6 = c.String(),
                        Input_161_т_12_р_10_к_3 = c.String(),
                        Input_162_т_12_р_10_к_4 = c.String(),
                        Input_163_т_12_р_10_к_5 = c.String(),
                        Input_164_т_12_р_10_к_6 = c.String(),
                        Input_165_т_12_р_11_к_3 = c.String(),
                        Input_166_т_12_р_11_к_4 = c.String(),
                        Input_167_т_12_р_11_к_5 = c.String(),
                        Input_168_т_12_р_11_к_6 = c.String(),
                        Input_169_т_12_р_12_к_3 = c.String(),
                        Input_170_т_12_р_12_к_4 = c.String(),
                        Input_171_т_12_р_12_к_5 = c.String(),
                        Input_172_т_12_р_12_к_6 = c.String(),
                        Input_173_т_12_р_13_к_3 = c.String(),
                        Input_174_т_12_р_13_к_4 = c.String(),
                        Input_175_т_12_р_13_к_5 = c.String(),
                        Input_176_т_12_р_13_к_6 = c.String(),
                        Input_177_т_12_р_14_к_3 = c.String(),
                        Input_178_т_12_р_14_к_4 = c.String(),
                        Input_179_т_12_р_14_к_5 = c.String(),
                        Input_180_т_12_р_14_к_6 = c.String(),
                        Input_181_т_12_р_15_к_3 = c.String(),
                        Input_182_т_12_р_15_к_4 = c.String(),
                        Input_183_т_12_р_15_к_5 = c.String(),
                        Input_184_т_12_р_15_к_6 = c.String(),
                        Input_185_т_12_р_16_к_3 = c.String(),
                        Input_186_т_12_р_16_к_4 = c.String(),
                        Input_187_т_12_р_16_к_5 = c.String(),
                        Input_188_т_12_р_16_к_6 = c.String(),
                        Input_189_т_12_р_17_к_3 = c.String(),
                        Input_190_т_12_р_17_к_4 = c.String(),
                        Input_191_т_12_р_17_к_5 = c.String(),
                        Input_192_т_12_р_17_к_6 = c.String(),
                        Input_193_т_12_р_18_к_3 = c.String(),
                        Input_194_т_12_р_18_к_4 = c.String(),
                        Input_195_т_12_р_18_к_5 = c.String(),
                        Input_196_т_12_р_18_к_6 = c.String(),
                        Input_197_т_12_р_19_к_3 = c.String(),
                        Input_198_т_12_р_19_к_4 = c.String(),
                        Input_199_т_12_р_19_к_5 = c.String(),
                        Input_200_т_12_р_19_к_6 = c.String(),
                        Input_201_т_12_р_20_к_3 = c.String(),
                        Input_202_т_12_р_20_к_4 = c.String(),
                        Input_203_т_12_р_20_к_5 = c.String(),
                        Input_204_т_12_р_20_к_6 = c.String(),
                        Input_205_т_12_р_21_к_3 = c.String(),
                        Input_206_т_12_р_21_к_4 = c.String(),
                        Input_207_т_12_р_21_к_5 = c.String(),
                        Input_208_т_12_р_21_к_6 = c.String(),
                        Input_209_т_12_р_22_к_3 = c.String(),
                        Input_210_т_12_р_22_к_4 = c.String(),
                        Input_211_т_12_р_22_к_5 = c.String(),
                        Input_212_т_12_р_22_к_6 = c.String(),
                        Input_213_т_12_р_23_к_3 = c.String(),
                        Input_214_т_12_р_23_к_4 = c.String(),
                        Input_215_т_12_р_23_к_5 = c.String(),
                        Input_216_т_12_р_23_к_6 = c.String(),
                        Input_217_т_12_р_24_к_3 = c.String(),
                        Input_218_т_12_р_24_к_4 = c.String(),
                        Input_219_т_12_р_24_к_5 = c.String(),
                        Input_220_т_12_р_24_к_6 = c.String(),
                        Input_221_місце_підпису = c.String(),
                        Input_222_п_і_б = c.String(),
                        Input_223_місце_підпису = c.String(),
                        Input_224_п_і_б = c.String(),
                        Input_225_телефон = c.String(),
                        Input_226_електронна_пошта = c.String(),
                        Input_226_факс = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.FormaN1",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Input_1_посада_роботодавця = c.String(),
                        Input_2_число = c.String(),
                        Input_3_місяць = c.String(),
                        Input_4_рік = c.String(),
                        Input_5_номер_акту = c.String(),
                        Input_6_п_і_б_потерпілого = c.String(),
                        Input_7_т_3_р_1_к_1 = c.String(),
                        Input_8_т_3_р_1_к_2 = c.String(),
                        Input_9_т_4_р_1_к_1 = c.String(),
                        Input_10_т_4_р_1_к_2 = c.String(),
                        Input_11_т_5_р_1_к_1 = c.String(),
                        Input_12_т_5_р_1_к_2 = c.String(),
                        Input_13_т_6_р_1_к_1 = c.String(),
                        Input_14_т_6_р_1_к_2 = c.String(),
                        Input_15_т_7_р_1_к_1 = c.String(),
                        Input_16_т_7_р_1_к_2 = c.String(),
                        Input_17_т_8_р_1_к_1 = c.String(),
                        Input_18_т_8_р_1_к_2 = c.String(),
                        Input_19_т_9_р_1_к_1 = c.String(),
                        Input_20_т_9_р_1_к_2 = c.String(),
                        Input_21_т_10_р_1_к_1 = c.String(),
                        Input_22_т_10_р_1_к_2 = c.String(),
                        Input_23_т_11_р_1_к_1 = c.String(),
                        Input_24_т_11_р_1_к_2 = c.String(),
                        Input_25_т_12_р_1_к_1 = c.String(),
                        Input_26_т_12_р_1_к_2 = c.String(),
                        Input_27_т_13_р_1_к_1 = c.String(),
                        Input_28_т_13_р_1_к_2 = c.String(),
                        Input_29_т_14_р_1_к_1 = c.String(),
                        Input_30_т_14_р_1_к_2 = c.String(),
                        Input_31_т_15_р_1_к_1 = c.String(),
                        Input_32_т_15_р_1_к_2 = c.String(),
                        Input_33_т_16_р_1_к_1 = c.String(),
                        Input_34_т_16_р_1_к_2 = c.String(),
                        Input_35_т_17_р_1_к_1 = c.String(),
                        Input_36_т_17_р_1_к_2 = c.String(),
                        Input_37_т_18_р_1_к_1 = c.String(),
                        Input_38_т_18_р_1_к_2 = c.String(),
                        Input_39_т_19_р_1_к_1 = c.String(),
                        Input_40_т_19_р_1_к_2 = c.String(),
                        Input_41_т_20_р_1_к_1 = c.String(),
                        Input_42_т_20_р_1_к_2 = c.String(),
                        Input_43_т_21_р_1_к_1 = c.String(),
                        Input_44_т_21_р_1_к_2 = c.String(),
                        Input_45_т_22_р_1_к_1 = c.String(),
                        Input_46_т_22_р_1_к_2 = c.String(),
                        Input_47_т_23_р_1_к_1 = c.String(),
                        Input_48_т_23_р_1_к_2 = c.String(),
                        Input_49_т_24_р_1_к_1 = c.String(),
                        Input_50_т_24_р_1_к_2 = c.String(),
                        Input_51_т_25_р_1_к_1 = c.String(),
                        Input_52_т_25_р_1_к_2 = c.String(),
                        Input_53_т_26_р_1_к_1 = c.String(),
                        Input_54_т_26_р_1_к_2 = c.String(),
                        Input_55_т_27_р_1_к_1 = c.String(),
                        Input_56_т_27_р_1_к_2 = c.String(),
                        Input_57_т_28_р_1_к_1 = c.String(),
                        Input_58_т_28_р_1_к_2 = c.String(),
                        Input_59_т_29_р_1_к_1 = c.String(),
                        Input_60_т_29_р_1_к_2 = c.String(),
                        Input_61_т_30_р_1_к_1 = c.String(),
                        Input_62_т_30_р_1_к_2 = c.String(),
                        Input_63_т_31_р_1_к_1 = c.String(),
                        Input_64_т_31_р_1_к_2 = c.String(),
                        Input_65_т_32_р_1_к_1 = c.String(),
                        Input_66_т_32_р_1_к_2 = c.String(),
                        Input_67_т_33_р_1_к_1 = c.String(),
                        Input_68_т_33_р_1_к_2 = c.String(),
                        Input_69_обставини_нещасності = c.String(),
                        Input_70_т_34_р_1_к_1 = c.String(),
                        Input_71_т_34_р_1_к_2 = c.String(),
                        Input_72_т_35_р_1_к_1 = c.String(),
                        Input_73_т_35_р_1_к_2 = c.String(),
                        Input_74_т_36_р_1_к_1 = c.String(),
                        Input_75_т_36_р_1_к_2 = c.String(),
                        Input_76_т_37_р_1_к_1 = c.String(),
                        Input_77_т_37_р_1_к_2 = c.String(),
                        Input_78_т_38_р_1_к_1 = c.String(),
                        Input_79_т_38_р_1_к_2 = c.String(),
                        Input_80_т_39_р_1_к_1 = c.String(),
                        Input_81_т_39_р_1_к_2 = c.String(),
                        Input_82_т_40_р_1_к_1 = c.String(),
                        Input_83_т_40_р_1_к_2 = c.String(),
                        Input_84_т_41_р_1_к_1 = c.String(),
                        Input_85_т_41_р_1_к_2 = c.String(),
                        Input_86_свідки_нещасності = c.String(),
                        Input_87_голова_комісії_посада = c.String(),
                        Input_88_голова_комісії_підпис = c.String(),
                        Input_89_ініціали_прізвище = c.String(),
                        Input_90_члени_комісії_посада = c.String(),
                        Input_91_члени_комісії_підпис = c.String(),
                        Input_92_члени_комісії_ініціали_прізвище = c.String(),
                        Input_93_члени_комісії_посада = c.String(),
                        Input_94_члени_комісії_підпис = c.String(),
                        Input_95_члени_комісії_ініціали_прізвище = c.String(),
                        Input_96_члени_комісії_посада = c.String(),
                        Input_97_члени_комісії_підпис = c.String(),
                        Input_98_члени_комісії_ініціали_прізвище = c.String(),
                        Input_99_число = c.String(),
                        Input_100_місяць = c.String(),
                        Input_101_рік = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.FormaN5",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Input_1_посада_роботодавця = c.String(),
                        Input_2_підпис = c.String(),
                        Input_3_ініціали_прізвище = c.String(),
                        Input_4_число = c.String(),
                        Input_5_місяць = c.String(),
                        Input_6_рік = c.String(),
                        Input_7_число = c.String(),
                        Input_8_місяць = c.String(),
                        Input_9_рік = c.String(),
                        Input_10_година = c.String(),
                        Input_11_хвилина = c.String(),
                        Input_12_п_і_б_професія_посада = c.String(),
                        Input_13_дата_складання_акта = c.String(),
                        Input_14_місце_складання_акта = c.String(),
                        Input_15_число = c.String(),
                        Input_16_місяць = c.String(),
                        Input_17_рік = c.String(),
                        Input_18_номер_акту = c.String(),
                        Input_19_найменування_органу = c.String(),
                        Input_20_голова_комісії_п_і_б = c.String(),
                        Input_21_голова_комісії_посада = c.String(),
                        Input_22_члени_комісії_п_і_б = c.String(),
                        Input_23_члени_комісії_посада = c.String(),
                        Input_24_участь_комісії_п_і_б = c.String(),
                        Input_25_участь_комісії_посада = c.String(),
                        Input_26_число = c.String(),
                        Input_27_місяць = c.String(),
                        Input_28_рік = c.String(),
                        Input_29_число = c.String(),
                        Input_30_місяць = c.String(),
                        Input_31_рік = c.String(),
                        Input_32_місце_події = c.String(),
                        Input_33_відомості_про_потерпілих = c.String(),
                        Input_34_характеристика_обєкта = c.String(),
                        Input_35_обставини_нещасності = c.String(),
                        Input_36_причини_нещасності = c.String(),
                        Input_37_заходи_усунення_нещасності = c.String(),
                        Input_38_висновки = c.String(),
                        Input_39_голова_комісії_підпис = c.String(),
                        Input_40_голова_комісії_ініціали = c.String(),
                        Input_41_члени_комісії_підпис = c.String(),
                        Input_42_члени_комісії_ініціали = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.FormaNpvs",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Input_1_посада_роботодавця = c.String(),
                        Input_2_число = c.String(),
                        Input_3_місяць = c.String(),
                        Input_4_рік = c.String(),
                        Input_5_номер_акта = c.String(),
                        Input_6_п_і_б_місце_проживання = c.String(),
                        Input_7_т_3_р_1_к_1 = c.String(),
                        Input_8_т_3_р_1_к_2 = c.String(),
                        Input_9_т_4_р_1_к_1 = c.String(),
                        Input_10_т_4_р_1_к_2 = c.String(),
                        Input_11_т_5_р_1_к_1 = c.String(),
                        Input_12_т_5_р_1_к_2 = c.String(),
                        Input_13_т_6_р_1_к_1 = c.String(),
                        Input_14_т_6_р_1_к_2 = c.String(),
                        Input_15_т_7_р_1_к_1 = c.String(),
                        Input_16_т_7_р_1_к_2 = c.String(),
                        Input_17_т_8_р_1_к_1 = c.String(),
                        Input_18_т_8_р_1_к_2 = c.String(),
                        Input_19_т_9_р_1_к_1 = c.String(),
                        Input_20_т_9_р_1_к_2 = c.String(),
                        Input_21_т_10_р_1_к_1 = c.String(),
                        Input_22_т_10_р_1_к_2 = c.String(),
                        Input_23_т_11_р_1_к_1 = c.String(),
                        Input_24_т_11_р_1_к_2 = c.String(),
                        Input_25_т_12_р_1_к_1 = c.String(),
                        Input_26_т_12_р_1_к_2 = c.String(),
                        Input_27_т_13_р_1_к_1 = c.String(),
                        Input_28_т_13_р_1_к_2 = c.String(),
                        Input_29_т_14_р_1_к_1 = c.String(),
                        Input_30_т_14_р_1_к_2 = c.String(),
                        Input_31_т_15_р_1_к_1 = c.String(),
                        Input_32_т_15_р_1_к_2 = c.String(),
                        Input_33_т_16_р_1_к_1 = c.String(),
                        Input_34_т_16_р_1_к_2 = c.String(),
                        Input_35_т_17_р_1_к_1 = c.String(),
                        Input_36_т_17_р_1_к_2 = c.String(),
                        Input_37_т_18_р_1_к_1 = c.String(),
                        Input_38_т_18_р_1_к_2 = c.String(),
                        Input_39_т_19_р_1_к_1 = c.String(),
                        Input_40_т_19_р_1_к_2 = c.String(),
                        Input_41_т_20_р_1_к_1 = c.String(),
                        Input_42_т_20_р_1_к_2 = c.String(),
                        Input_43_т_21_р_1_к_1 = c.String(),
                        Input_44_т_21_р_1_к_2 = c.String(),
                        Input_45_т_22_р_1_к_1 = c.String(),
                        Input_46_т_22_р_1_к_2 = c.String(),
                        Input_47_т_23_р_1_к_1 = c.String(),
                        Input_48_т_23_р_1_к_2 = c.String(),
                        Input_49_т_24_р_1_к_1 = c.String(),
                        Input_50_т_24_р_1_к_2 = c.String(),
                        Input_51_т_25_р_1_к_1 = c.String(),
                        Input_52_т_25_р_1_к_2 = c.String(),
                        Input_53_т_26_р_1_к_1 = c.String(),
                        Input_54_т_26_р_1_к_2 = c.String(),
                        Input_55_т_27_р_1_к_1 = c.String(),
                        Input_56_т_27_р_1_к_2 = c.String(),
                        Input_57_т_28_р_1_к_1 = c.String(),
                        Input_58_т_28_р_1_к_2 = c.String(),
                        Input_59_т_29_р_1_к_1 = c.String(),
                        Input_60_т_29_р_1_к_2 = c.String(),
                        Input_61_т_30_р_1_к_1 = c.String(),
                        Input_62_т_30_р_1_к_2 = c.String(),
                        Input_63_т_31_р_1_к_1 = c.String(),
                        Input_64_т_31_р_1_к_2 = c.String(),
                        Input_65_т_32_р_1_к_1 = c.String(),
                        Input_66_т_32_р_1_к_2 = c.String(),
                        Input_67_т_33_р_1_к_1 = c.String(),
                        Input_68_т_33_р_1_к_2 = c.String(),
                        Input_69_обставини_нещасності = c.String(),
                        Input_70_т_34_р_1_к_1 = c.String(),
                        Input_71_т_34_р_1_к_2 = c.String(),
                        Input_72_т_35_р_1_к_1 = c.String(),
                        Input_73_т_35_р_1_к_2 = c.String(),
                        Input_74_т_36_р_1_к_1 = c.String(),
                        Input_75_т_36_р_1_к_2 = c.String(),
                        Input_76_т_37_р_1_к_1 = c.String(),
                        Input_77_т_37_р_1_к_2 = c.String(),
                        Input_78_т_38_р_1_к_1 = c.String(),
                        Input_79_т_38_р_1_к_2 = c.String(),
                        Input_80_т_39_р_1_к_1 = c.String(),
                        Input_81_т_39_р_1_к_2 = c.String(),
                        Input_82_т_40_р_1_к_1 = c.String(),
                        Input_83_т_40_р_1_к_2 = c.String(),
                        Input_84_т_41_р_1_к_1 = c.String(),
                        Input_85_т_41_р_1_к_2 = c.String(),
                        Input_86_5_заходи_усунення_нещасності = c.String(),
                        Input_86_свідки_нещасності = c.String(),
                        Input_87_голова_комісії_посада = c.String(),
                        Input_88_голова_комісії_підпис = c.String(),
                        Input_89_ініціали_прізвище = c.String(),
                        Input_90_члени_комісії_посада = c.String(),
                        Input_91_члени_комісії_підпис = c.String(),
                        Input_92_члени_комісії_ініціали_прізвище = c.String(),
                        Input_93_члени_комісії_посада = c.String(),
                        Input_94_члени_комісії_підпис = c.String(),
                        Input_95_члени_комісії_ініціали_прізвище = c.String(),
                        Input_96_члени_комісії_посада = c.String(),
                        Input_97_члени_комісії_підпис = c.String(),
                        Input_98_члени_комісії_ініціали_прізвище = c.String(),
                        Input_99_число = c.String(),
                        Input_100_місяць = c.String(),
                        Input_101_рік = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.FormaNts",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Input_1_посада_роботодавця = c.String(),
                        Input_2_число = c.String(),
                        Input_3_місяць = c.String(),
                        Input_4_рік = c.String(),
                        Input_5_номер_акта = c.String(),
                        Input_6_п_і_б = c.String(),
                        Input_7_т_3_р_1_к_1 = c.String(),
                        Input_8_т_3_р_1_к_2 = c.String(),
                        Input_9_т_4_р_1_к_1 = c.String(),
                        Input_10_т_4_р_1_к_2 = c.String(),
                        Input_11_т_5_р_1_к_1 = c.String(),
                        Input_12_т_5_р_1_к_2 = c.String(),
                        Input_13_т_6_р_1_к_1 = c.String(),
                        Input_14_т_6_р_1_к_2 = c.String(),
                        Input_15_т_6_р_1_к_3 = c.String(),
                        Input_16_т_6_р_1_к_4 = c.String(),
                        Input_17_т_6_р_1_к_5 = c.String(),
                        Input_18_т_6_р_1_к_6 = c.String(),
                        Input_19_т_6_р_1_к_7 = c.String(),
                        Input_20_т_7_р_1_к_1 = c.String(),
                        Input_21_т_7_р_1_к_2 = c.String(),
                        Input_22_т_7_р_1_к_3 = c.String(),
                        Input_23_т_7_р_1_к_4 = c.String(),
                        Input_24_т_7_р_1_к_5 = c.String(),
                        Input_25_т_8_р_1_к_1 = c.String(),
                        Input_26_т_8_р_1_к_2 = c.String(),
                        Input_27_т_9_р_1_к_1 = c.String(),
                        Input_28_т_9_р_1_к_2 = c.String(),
                        Input_29_т_10_р_1_к_1 = c.String(),
                        Input_30_т_10_р_1_к_2 = c.String(),
                        Input_31_т_11_р_1_к_1 = c.String(),
                        Input_32_т_11_р_1_к_2 = c.String(),
                        Input_33_т_12_р_1_к_1 = c.String(),
                        Input_34_т_12_р_1_к_2 = c.String(),
                        Input_35_стислий_виклад_обставин = c.String(),
                        Input_36_т_13_р_1_к_1 = c.String(),
                        Input_37_т_13_р_1_к_2 = c.String(),
                        Input_38_т_14_р_1_к_1 = c.String(),
                        Input_39_т_14_р_1_к_2 = c.String(),
                        Input_40_т_15_р_1_к_1 = c.String(),
                        Input_41_т_15_р_1_к_2 = c.String(),
                        Input_42_т_16_р_1_к_1 = c.String(),
                        Input_43_т_16_р_1_к_2 = c.String(),
                        Input_44_висновки = c.String(),
                        Input_45_т_17_р_1_к_1 = c.String(),
                        Input_46_т_17_р_1_к_2 = c.String(),
                        Input_47_голова_комісії_посада = c.String(),
                        Input_48_голова_комісії_підпис = c.String(),
                        Input_49_голова_комісії_ініціали = c.String(),
                        Input_50_члени_комісії_посада = c.String(),
                        Input_51_члени_комісії_підпис = c.String(),
                        Input_52_члени_комісії_ініціали = c.String(),
                        Input_53_члени_комісії_посада = c.String(),
                        Input_54_члени_комісії_підпис = c.String(),
                        Input_55_члени_комісії_ініціали = c.String(),
                        Input_56_число = c.String(),
                        Input_57_місяць = c.String(),
                        Input_58_рік = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.FormaZvts",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Input_1_назва_організації_профспілки = c.String(),
                        Input_2_рік = c.String(),
                        Input_3_кількість_інспекторів_гаджетів = c.String(),
                        Input_4_т_3_р_4_к_2 = c.String(),
                        Input_5_т_3_р_4_к_3 = c.String(),
                        Input_6_т_3_р_5_к_2 = c.String(),
                        Input_7_т_3_р_5_к_3 = c.String(),
                        Input_8_т_3_р_6_к_2 = c.String(),
                        Input_9_т_3_р_6_к_3 = c.String(),
                        Input_10_т_3_р_7_к_2 = c.String(),
                        Input_11_т_3_р_7_к_3 = c.String(),
                        Input_12_т_3_р_8_к_2 = c.String(),
                        Input_13_т_3_р_8_к_3 = c.String(),
                        Input_14_т_3_р_9_к_2 = c.String(),
                        Input_15_т_3_р_9_к_3 = c.String(),
                        Input_16_т_3_р_10_к_2 = c.String(),
                        Input_17_т_3_р_10_к_3 = c.String(),
                        Input_18_т_3_р_11_к_2 = c.String(),
                        Input_19_т_3_р_11_к_3 = c.String(),
                        Input_20_т_3_р_12_к_2 = c.String(),
                        Input_21_т_3_р_12_к_3 = c.String(),
                        Input_22_тех_інспектор_праці_1 = c.String(),
                        Input_23_тех_інспектор_праці_2 = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.FormaZvts");
            DropTable("dbo.FormaNts");
            DropTable("dbo.FormaNpvs");
            DropTable("dbo.FormaN5");
            DropTable("dbo.FormaN1");
            DropTable("dbo.Forma7");
            DropTable("dbo.DynamicTables");
            DropTable("dbo.Dodatoc5");
            DropTable("dbo.Dodatoc4");
            DropTable("dbo.Dodatoc2");
            DropTable("dbo.Dodatoc1");
        }
    }
}
